FROM golang:alpine as build
WORKDIR /build
COPY ./go.mod ./
COPY ./go.sum ./go.sum
RUN go mod download
COPY . .
RUN go build -o ./target_srv ./target/*.go

FROM alpine
COPY --from=build /build/target_srv /app/target_srv
EXPOSE 8000
CMD ["/app/target_srv"]